apiVersion: apps/v1     #defines the object to be ReplicaSet
kind: ReplicaSet        # Replicaset is not available on v1
metadata:         
  name: myrs
spec:
  replicas: 2          # this element defines the desired number of pods
  selector:
    matchExpressions:       # These must match the labels
      - {key: myname, operator: In, values: [prasad, prasadd, prasaaad]}
      - {key: env, operator: NotIn, values: [production]}
  template:
    metadata:
      name: testpod7
      labels:
        myname: prasad
    spec:
      containers: 
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello-Prasad; sleep 5; done"]
